name: WebUI CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      with:
        profile: minimal
        toolchain: stable
    - name: test
      run: |
        EXTRA_CFLAGS=-fPIC make -C plugin/smartdns-ui test -j8
